export const SET_NEEDKEEP = 'SET_NEEDKEEP'

export const SET_WARNINGSCROLL = 'SET_WARNINGSCROLL'

export const SET_OFFICIAL = 'SET_OFFICIAL'

export const SET_PRODUCTION = 'SET_PRODUCTION'

export const SET_VEHICLEAPPROVAL = 'SET_VEHICLEAPPROVAL'

export const SET_VEHICLESCHEDULING = 'SET_VEHICLESCHEDULING'

export const SET_REGISTRATION = 'SET_REGISTRATION'

export const SET_EVALUATE = 'SET_EVALUATE'

export const SET_DILIGENTFRUGAL = 'SET_DILIGENTFRUGAL'

export const SET_REFUELING = 'SET_REFUELING'

export const SET_MAINTENANCE = 'SET_MAINTENANCE'

export const SET_UPKEEP = 'SET_UPKEEP'
